=== MarkBilginer/MusicLandscape/TrackContainer.dtd
<!ELEMENT TrackContainer (Track+)>
<!ELEMENT Track (Title,Writer,Performer,Duration,Year)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Writer (#PCDATA)>
<!ELEMENT Performer (#PCDATA)>
<!ELEMENT Duration (#PCDATA)>
<!ELEMENT Year (#PCDATA)>

=== MarkBilginer/MusicLandscape/metallica_tracks.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE TrackContainer SYSTEM "TrackContainer.dtd">
<TrackContainer>
    <Track>
        <Title>Creeping Death</Title>
        <Writer>Hetfield Ulrich Burton Hammett</Writer>
        <Performer>Metallica</Performer>
        <Duration>384</Duration>
        <Year>1984</Year>
    </Track>
    <Track>
        <Title>Enter Sandman</Title>
        <Writer>Hetfield Ulrich Hammett</Writer>
        <Performer>Metallica</Performer>
        <Duration>331</Duration>
        <Year>1991</Year>
    </Track>
    <Track>
        <Title>Fight Fire with Fire</Title>
        <Writer>Hetfield Ulrich Burton</Writer>
        <Performer>Metallica</Performer>
        <Duration>266</Duration>
        <Year>1984</Year>
    </Track>
    <Track>
        <Title>Master of Puppets</Title>
        <Writer>Hetfield Ulrich Burton Hammett</Writer>
        <Performer>Metallica</Performer>
        <Duration>466</Duration>
        <Year>1986</Year>
    </Track>
    <Track>
        <Title>Nothing Else Matters</Title>
        <Writer>Hetfield Ulrich</Writer>
        <Performer>Metallica</Performer>
        <Duration>388</Duration>
        <Year>1991</Year>
    </Track>
    <Track>
        <Title>One</Title>
        <Writer>Hetfield Ulrich Hammet</Writer>
        <Performer>Metallica</Performer>
        <Duration>424</Duration>
        <Year>1986</Year>
    </Track>
    <Track>
        <Title>Ride the Lightning</Title>
        <Writer>Hetfield Ulrich Burton Mustaine</Writer>
        <Performer>Metallica</Performer>
        <Duration>386</Duration>
        <Year>1984</Year>
    </Track>
    <Track>
        <Title>Sad but true</Title>
        <Writer>Hetfield Ulrich</Writer>
        <Performer>Metallica</Performer>
        <Duration>325</Duration>
        <Year>1991</Year>
    </Track>
    <Track>
        <Title>Seek and Destroy</Title>
        <Writer>Hetfield Ulrich</Writer>
        <Performer>Metallica</Performer>
        <Duration>396</Duration>
        <Year>1983</Year>
    </Track>
    <Track>
        <Title>The Four Horsemen</Title>
        <Writer>Hetfield Ulrich Mustaine</Writer>
        <Performer>Metallica</Performer>
        <Duration>422</Duration>
        <Year>1983</Year>
    </Track>
    <Track>
        <Title>The Unforgiven</Title>
        <Writer>Hetfield Ulrich Hammett</Writer>
        <Performer>Metallica</Performer>
        <Duration>387</Duration>
        <Year>1991</Year>
    </Track>
    <Track>
        <Title>Time</Title>
        <Writer>Roger Waters</Writer>
        <Performer>Pink Floyd</Performer>
        <Duration>424</Duration>
        <Year>1973</Year>
    </Track>
</TrackContainer>
